version: '3.4'

services:
  randomatedatamanager:
    image: ${DOCKER_REGISTRY-}randomatedatamanager
    build:
      context: .
      dockerfile: RandomAteDataManager/Dockerfile
    ports:
        - "80:80" 
        - "433:433" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost;http://localhost
      - ASPNETCORE_HTTPS_PORT=44349

  randomate-mongo:
    image: mongo
